import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync, mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { buildBackendContractFiles, BACKEND_CONTRACT_PATHS, BACKEND_SOURCES, buildClosureContractFiles, CLOSURE_CONTRACT_PATHS, CLOSURE_DELTA_PATH } from '../../business-docs/08-工具/build_customer_agent_backend_contract.mjs';
import { OWNER_SQL_SOURCES, OWNER_PROFILE_PATH, OWNER_CONTRACT_PATHS } from '../../business-docs/08-工具/build_customer_agent_owner_contract.mjs';
import { CONTRACT_SOURCE_PATHS, loadContractSetFromCommit } from '../../business-docs/08-工具/export_customer_agent_contract_set.mjs';
const read = source => readFileSync(new URL(`../../${source}`,import.meta.url));
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const generated = buildBackendContractFiles(read);
const parser = createRequire(import.meta.url)('@libpg-query/parser');
await parser.loadModule();
test('integrated backend contract preserves predecessor and parses complete SQL',()=>{
 for (const key of ['database','openapi']) assert.ok(read(BACKEND_CONTRACT_PATHS[key]).equals(generated[key]),key);
 assert.ok(generated.database.includes(read(OWNER_CONTRACT_PATHS.database)));
 assert.ok(parser.parseSync(generated.database.toString()).stmts.length>550);
 assert.ok(parser.parsePlPgSQLSync(generated.database.toString()).plpgsql_funcs.length>100);
 const api=generated.openapi.toString();
 assert.match(api,/version: 1.13.0/);
 for (const [route,item] of Object.entries(JSON.parse(read(BACKEND_SOURCES.openapi)).paths)) {
  const line=api.split('\n').find(line=>line.startsWith(`  ${JSON.stringify(route)}:`));
  const actual=JSON.parse(line.slice(line.indexOf(': ')+2));
  for(const method of Object.keys(item)) assert.deepEqual(actual[method].security,item[method].security??[{ProductSession:[]}]);
 }
});
for (const closure of [false, true]) test(`fixed-commit export validates generated bytes, approval and immutable predecessor (closure=${closure})`,()=>{
 const selected = closure ? buildClosureContractFiles(read) : generated;
 const selectedPaths = closure ? CLOSURE_CONTRACT_PATHS : BACKEND_CONTRACT_PATHS;
 const repo=mkdtempSync(path.join(tmpdir(),'backend-export-'));
 const git=(...args)=>execFileSync('git',args,{cwd:repo,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
 const write=(file,bytes)=>{mkdirSync(path.dirname(path.join(repo,file)),{recursive:true});writeFileSync(path.join(repo,file),bytes);};
 try {
  const development=path.posix.dirname(OWNER_PROFILE_PATH);
  const approval='business-docs/01-客服Agent项目/90-评审/2026-09-09_后端合成开发批准.md';
  const files=new Set([...Object.values(CONTRACT_SOURCE_PATHS),...OWNER_SQL_SOURCES,...Object.values(OWNER_CONTRACT_PATHS),...Object.values(BACKEND_CONTRACT_PATHS),...Object.values(BACKEND_SOURCES),OWNER_PROFILE_PATH,approval,`${development}/owner-acceptance.v1.schema.json`,`${development}/owner-acceptance.registry.v1.openapi-extension.json`]);
  if (closure) for (const file of [...Object.values(CLOSURE_CONTRACT_PATHS),CLOSURE_DELTA_PATH]) files.add(file);
  for(const file of files) write(file,read(file));
  write(OWNER_PROFILE_PATH,JSON.stringify({schema:'customer-agent-contract-profile/v1',profile:closure?'backend-closure-v1':'backend-synthetic-v1'}));
  git('init','-q');git('config','user.email','synthetic@example.invalid');git('config','user.name','Synthetic');
  const commit=()=>{git('add','--all');git('commit','-qm','synthetic contract fixture');return git('rev-parse','HEAD');};
  const options={repository:repo,sourceGitSha:commit(),expectedOpenapiSha256:hash(selected.openapi),expectedDatabaseSha256:hash(selected.database)};
  assert.equal(loadContractSetFromCommit(options).manifest.database.version,closure?'schema.v1.17':'schema.v1.16');
  // Working-tree drift must not affect immutable reads.
  write(approval,read(approval).toString().replace('状态：APPROVED','状态：NOT APPROVED'));
  assert.equal(loadContractSetFromCommit(options).manifest.openapi.version,'1.13.0');
  assert.throws(()=>loadContractSetFromCommit({...options,sourceGitSha:commit()}),/缺后端合成开发批准/);
  write(approval,read(approval));
  const altered=Buffer.concat([selected.database,Buffer.from('\n-- drift\n')]);write(selectedPaths.database,altered);
  assert.throws(()=>loadContractSetFromCommit({...options,sourceGitSha:commit(),expectedDatabaseSha256:hash(altered)}),/派生产物/);
  write(selectedPaths.database,selected.database);
  if (closure) {
    write(OWNER_PROFILE_PATH,JSON.stringify({schema:'customer-agent-contract-profile/v1',profile:'backend-synthetic-v1'}));
    assert.throws(()=>loadContractSetFromCommit({...options,sourceGitSha:commit()}),/拒绝降级 closure profile/);
  }
  write(OWNER_PROFILE_PATH,JSON.stringify({schema:'customer-agent-contract-profile/v1',profile:'owner-acceptance-v1'}));
  assert.throws(()=>loadContractSetFromCommit({...options,sourceGitSha:commit()}),/拒绝降级/);
 } finally {rmSync(repo,{recursive:true,force:true});}
});
