#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildOwnerContractFiles } from './build_customer_agent_owner_contract.mjs';

const development = 'business-docs/01-客服Agent项目/30-开发-进行中';
export const BACKEND_CONTRACT_PATHS = Object.freeze({
  openapi: `${development}/openapi.v1.13.yaml`,
  database: `${development}/schema.v1.16.sql`,
  increment: `${development}/09-后端合成开发合同交接.md`,
});
export const BACKEND_SOURCES = Object.freeze({
  openapi: `${development}/backend-runtime-candidate/openapi.delta.json`,
  storage: `${development}/backend-runtime-candidate/storage.delta.sql`,
  transactions: `${development}/backend-runtime-candidate/transactions.delta.sql`,
});
const digest = bytes => createHash('sha256').update(bytes).digest('hex');

// Preserve the predecessor bytes and append bounded, fixed-source increments. JSON values
// are valid YAML flow values; exact anchors fail closed if the predecessor layout changes.
export function buildBackendContractFiles(readSource) {
  const base = buildOwnerContractFiles(readSource);
  const delta = JSON.parse(readSource(BACKEND_SOURCES.openapi));
  let openapi = base.openapi.toString('utf8');
  const insert = (anchor, value) => {
    if (openapi.split(anchor).length !== 2) throw new Error(`Non-unique backend anchor: ${anchor}`);
    openapi = openapi.replace(anchor, anchor + value);
  };
  if (!openapi.includes('  version: 1.12.0\n')) throw new Error('Backend predecessor must be 1.12.0');
  openapi = openapi.replace('  version: 1.12.0\n', '  version: 1.13.0\n');
  for (const [route, item] of Object.entries(delta.paths)) {
    if (openapi.includes(`  ${route}:`)) throw new Error(`Backend route collision: ${route}`);
    const operations = Object.fromEntries(Object.entries(item).map(([method, operation]) => {
      if (!['get','post','put','patch','delete','options','head','trace'].includes(method)) throw new Error(`Unsupported path item: ${method}`);
      return [method, {...operation, security: operation.security ?? delta.security}];
    }));
    insert('paths:\n', `  ${JSON.stringify(route)}: ${JSON.stringify(operations)}\n`);
  }
  for (const [section, members] of Object.entries(delta.components)) {
    if (!['schemas','securitySchemes'].includes(section)) throw new Error(`Unsupported components: ${section}`);
    for (const [name, value] of Object.entries(members)) {
      if (!/^[A-Za-z][A-Za-z0-9]*$/.test(name) || openapi.includes(`    ${name}:`)) throw new Error(`Backend component collision: ${name}`);
      insert(`  ${section}:\n`, `    ${name}: ${JSON.stringify(value)}\n`);
    }
  }
  for (const tag of delta.tags) insert('\ntags:\n', `  - ${JSON.stringify(tag)}\n`);
  // Existing operations retain bearerAuth references; redefine only their credential semantics.
  const bearer = /    bearerAuth:\n[\s\S]*?(?=    mockUser:)/;
  if (!bearer.test(openapi)) throw new Error('Missing predecessor bearer scheme');
  openapi = openapi.replace(bearer, '    bearerAuth: '+JSON.stringify({type:'http',scheme:'bearer',bearerFormat:'Opaque product session',description:'产品会话，服务端按数据库当前主体资格认证；禁止把提供方 token、客户端角色或可本地验签的 JWT 当作产品身份。mock 仅限显式开发测试配置。'})+'\n');
  openapi += '\nx-backend-development: '+JSON.stringify({status:'SYNTHETIC_DEVELOPMENT_ONLY',approval:'DEC-BACKEND-SYNTHETIC-20260909',runtime_activated:false,sqlContract:'schema.v1.16'})+'\n';
  const database = '-- schema.v1.16 — synthetic backend integrated clean-install reference\n'
    + '-- GENERATED by build_customer_agent_backend_contract.mjs; not an in-place migration.\n'
    + base.database.toString('utf8') + '\n'
    + ['storage','transactions'].map(key => {
      const source = BACKEND_SOURCES[key], bytes = readSource(source);
      return `-- BEGIN SOURCE ${source}\n-- SHA256 ${digest(bytes)}\n${bytes.toString('utf8')}\n-- END SOURCE ${source}\n`;
    }).join('\n')
    + "\nBEGIN;\nCOMMENT ON SCHEMA public IS 'CS-AI-C11 schema.v1.16; synthetic backend development only; runtime activation and production NOT_CERTIFIED';\nCOMMIT;\n";
  return {openapi:Buffer.from(openapi), database:Buffer.from(database)};
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.length !== 1 || !['--write','--check'].includes(args[0])) throw new Error('Use --write or --check');
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
  const files = buildBackendContractFiles(source => readFileSync(path.join(root,source)));
  for (const [key,bytes] of Object.entries(files)) {
    const target = path.join(root,BACKEND_CONTRACT_PATHS[key]);
    if (args[0] === '--write') writeFileSync(target,bytes);
    else if (!readFileSync(target).equals(bytes)) throw new Error(`Backend generated drift: ${key}`);
    console.log(`${key} ${digest(bytes)} ${bytes.length} bytes`);
  }
}
