#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const design = 'business-docs/01-客服Agent项目/20-设计-进行中';
const development = 'business-docs/01-客服Agent项目/30-开发-进行中';
export const OWNER_PROFILE_PATH = `${development}/contract-profile.v1.json`;
export const OWNER_CONTRACT_PATHS = Object.freeze({
  openapi: `${development}/openapi.v1.12.yaml`,
  database: `${development}/schema.v1.15.sql`,
  increment: `${development}/08-A3负责人承接合同交接.md`,
});
export const OWNER_SQL_SOURCES = Object.freeze([
  `${design}/33-schema-v1-草案.sql`,
  ...['registry', 'content-hash', 'content-scope', 'storage', 'import', 'publish']
    .map((name) => `${development}/owner-acceptance.${name}.v1.sql`),
]);
const digest = (bytes) => createHash('sha256').update(bytes).digest('hex');

// Both working-tree generation and immutable Git export use the same composition contract.
// All input paths are fixed here; a profile can never redirect reads to arbitrary files.
export function buildOwnerContractFiles(readSource) {
  const database = '-- schema.v1.15 — owner acceptance integrated clean-install reference\n'
    + '-- GENERATED by build_customer_agent_owner_contract.mjs; edit canonical inputs only.\n'
    + '-- Not an in-place upgrade or runtime activation. Preserve immutable product migrations.\n\n'
    + OWNER_SQL_SOURCES.map((source) => {
      const bytes = readSource(source);
      return `-- BEGIN SOURCE ${source}\n-- SHA256 ${digest(bytes)}\n${bytes.toString('utf8')}\n-- END SOURCE ${source}\n`;
    }).join('\n')
    + "\n-- BEGIN INTEGRATED SCHEMA MARKER\nBEGIN;\nCOMMENT ON SCHEMA public IS 'CS-AI-C11 schema.v1.15; bounded owner acceptance g1a_offline_only; legacy single/dual review retained; runtime activation, managed PostgreSQL, backup/restore and production remain NOT_CERTIFIED; Phase1 rewrite/auto_send/training hard-off';\nCOMMIT;\n-- END INTEGRATED SCHEMA MARKER\n";
  let openapi = readSource(`${design}/openapi.v1.yaml`).toString('utf8');
  const oldMode = '    ReviewMode:\n      type: string\n      enum: [single, dual]';
  if (!openapi.includes('  version: 1.11.0\n') || openapi.split(oldMode).length !== 2) {
    throw new Error('Owner contract requires the exact predecessor OpenAPI version and ReviewMode');
  }
  openapi = openapi.replace('  version: 1.11.0\n', '  version: 1.12.0\n')
    .replace(oldMode, oldMode.replace('[single, dual]', '[single, dual, owner_acceptance]'));
  const schema = JSON.parse(readSource(`${development}/owner-acceptance.v1.schema.json`));
  // Inline local $defs so the two-file exported contract has no external schema dependencies.
  const inline = (node) => {
    if (Array.isArray(node)) return node.map(inline);
    if (!node || typeof node !== 'object') return node;
    if (node.$ref) {
      const name = node.$ref.replace(/^#\/\$defs\//, '');
      if (!schema.$defs[name] || Object.keys(node).length !== 1) throw new Error('Unsupported owner schema reference');
      return inline(schema.$defs[name]);
    }
    return Object.fromEntries(Object.entries(node).filter(([key]) => !['$defs', '$id', '$schema'].includes(key))
      .map(([key, value]) => [key, inline(value)]));
  };
  const component = '    OwnerAcceptanceRecord: ' + JSON.stringify(inline(schema)) + '\n';
  if (openapi.split('  schemas:\n').length !== 2) throw new Error('OpenAPI schemas anchor must be unique');
  openapi = openapi.replace('  schemas:\n', '  schemas:\n' + component);
  const candidate = JSON.parse(readSource(`${development}/owner-acceptance.registry.v1.openapi-extension.json`))
    ['x-owner-acceptance-registry-candidate'];
  const extension = {
    ...candidate,
    status: 'INTEGRATED_CONTRACT_NOT_ACTIVATED',
    sqlContract: 'schema.v1.15',
    changesExistingReviewMode: true,
    recordSchemaComponent: '#/components/schemas/OwnerAcceptanceRecord',
    description: '完整承接合同，限 g1a_offline_only。登记主体须独立核验包外批准锚点；无新增 HTTP 路由，不签发真实数据或运行权限。',
  };
  openapi = '# GENERATED by build_customer_agent_owner_contract.mjs; edit canonical inputs only.\n'
    + openapi + '\nx-owner-acceptance-registry: ' + JSON.stringify(extension) + '\n';
  return { database: Buffer.from(database), openapi: Buffer.from(openapi) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.length !== 1 || !['--write', '--check'].includes(args[0])) throw new Error('Use --write or --check');
  const files = buildOwnerContractFiles((source) => readFileSync(path.join(root, source)));
  for (const [key, bytes] of Object.entries(files)) {
    const target = path.join(root, OWNER_CONTRACT_PATHS[key]);
    if (args[0] === '--write') writeFileSync(target, bytes);
    else if (!readFileSync(target).equals(bytes)) throw new Error(`Generated contract drift: ${key}`);
    console.log(`${key} ${digest(bytes)} ${bytes.length} bytes`);
  }
}
